language: python
os: linux
sudo: required
branches:
  only:
  - master
services:
- docker
matrix:
  include:
  - python: '3.7'
    dist: xenial
    sudo: true
  - python: '2.7'
    if: type != pull_request
install:
- echo "$TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION $PYTHON"
- |
  if [[ "$TRAVIS_BRANCH" == "stable" ]] ; then
      pip install cibuildwheel==0.9.4 twine
  else
      if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]] ; then
          pip install coverage coveralls
      fi
  fi
script:
- pip install .
- pingit list
- pingit export -p ..
- pingit export -p .. -o ../structure.json
- pingit import -i ../structure.json -o ../import
- pingit fetch -p ..
- pingit pull --rebase -p ..
- pingit status -p ..
- pingit archive -p .. -o ../backup
- pingit archive -p .. -o ../backup --no-timestamp
- pingit archive -p .. -o ../backup --format zip
- ls -l ../*/*/*
deploy:
  provider: pypi
  skip_existing: true
  distributions: sdist bdist_wheel
  tags: true
  on:
    branch: master
    python: 3.7
  user:
    secure: RXz4U45i13gHmtDV8raEu+2KD98SQpPDhuIgRZAV7Lf1jkhXmDLxYxoC6ijBYV5dk3DoGNuQ8kdEAWiW/s1wGPJmSz7ER7tguZ8AEw+TusFp5x5e9OGA28AYh/lRiw8UrCs1nk4eZU16OxwIOkiWQsW1SZ4cSAEjr2vVyg2YD7B9s0xFowsEMC1rA3fFmMpL1TKe0KCyPKQJGloPGMRclejcZMIBGMwu6RG1RO2YjcGwp+o9koPqnmXeFVPMpFUqXlyvRackPSGZz14ZjdutqKdi4v/ES9OVUDXpwMNhjXAWAt2GGJUp0XXNZGxQm285cJk2FRK4fQxRvgztoZOC9vo7Ap6DjkCiN09hrnL7rnDfpCApzdjzFg29AOWkt9lPA4hNbZfI1UkbSdaMrRYxKbwdB+jHU9/hxkVrLurCjN9kIJKFpqEuQc+UCnAOKgxO9GcYKp3BLSX8nxyNKWyDBvLws9x9m/8jNUzxQhOPFSMmFHEX8ijaN7ZdkV9VaXNIEmLWlySbRWmF0HVDQkrn9dpad2N/w0d3djffzWKHjT4IWUkNpZW0T4XNhpwPIl7s6Gq/GBQG5c/wgSu3S/0MEYkqLvdW0DcMOCObiQzjM+Ubu6GjiHs2AFAZDGmUJ8lhIkQZdLrtz8Xzd8kjqyI8DlbWj2D1Vj48Dt4Kd/OJYVY=
  password:
    secure: IS1Sgz7eihwpytniOzHYf8cOFdQodwwixcdBayTB11c9pF6y2LFf1BlLpk9nld26t7E+vRF1GrTKkoYreEqcSvbAN8DE5frZBYNUEMRMaAKiuouQ1bXErQArRMAesCuj0U/1UMXjJ1X7VLjSHZSJmc7iXCmmim4uSJP2PPDRq6+6hFN25b7xvvOmAVKNn+vDSzoKACBLhRYH9Tsh7TEx6h7VQYYDApOt6RhnExJwDcRFfaiZ+UcDtrh7ezY3TXMp0zEpl8XTWYCgs38ko6f9KaeFGgs9AFx4YoWafHmc8oxPMYylPH9eoKfMjgyw0BMq3TqEw9j3rfdt4w0gVrKccaGUtOqfc+WdVOfxbzS2DxNXS+5k7YQS5Wpq78439p+i1b86tTza1JkKem1Fz62RlRgsEDMjp0Y4u1ynsW1LqLAUDzISPRnwwpPQ+zL46a0iE6+SWBiGDn4VMHfw0aV38eZRrxJ9yE2pGr4zvu2d9cK9NBl+naoKMF9JFhqsCNr731c/DXJV84T4/Cu+Yebb6a5THsCJR3k5rcvm7gG2MfZSjNyjoXixkCGOfpgcJSJyjbTxLyBgZIGDWxs6Fa4Pvbp4NX7V0DKeT+m6AsGzrNla4j086FkFM202SjIh5X6ynNXRyL1C7eXvUJnZE1DDHc/5d2F8eWzb136am7sfaTA=
