language: python
os: linux
sudo: required
branches:
  only:
  - master
services:
- docker
matrix:
  include:
  - python: '3.7'
    dist: xenial
    sudo: true
  - python: '2.7'
    if: type != pull_request
install:
- echo "$TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION $PYTHON"
- |
  if [[ "$TRAVIS_BRANCH" == "stable" ]] ; then
      pip install cibuildwheel==0.9.4 twine
  else
      if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]] ; then
          pip install coverage coveralls
      fi
  fi
script:
- pip install .
- pingit list
- pingit export -p ..
- pingit export -p .. -o ../structure.json
- pingit import -i ../structure.json -o ../import
- pingit fetch -p ..
- pingit pull --rebase -p ..
- pingit status -p ..
- pingit archive -p .. -o ../backup
- pingit archive -p .. -o ../backup --no-timestamp
- pingit archive -p .. -o ../backup --format zip
- ls -l ../*/*/*
deploy:
  provider: pypi
  skip_existing: true
  distributions: sdist bdist_wheel
  tags: true
  on:
    branch: master
    python: 3.7
  user:
    secure: QHLGLV5h9QU+zaO3P/ww4CagKJucfT11z6DPzApQ6HWFpQolWyVg2uElkp4qv5E9X1lWAOLXapJl0J6k9mwPW7GAryIf/7umaeyXvrV78bgNiiFOwtb+uYi/alQ5GOJfwfD/aem5m/RL/hAd+KQU1CqqiPGfVsJKmIA2F9RgdrfDaSjlnd+w38e7XGtQlS8UmDGhOLqwGtOlPfJ2FAyaDMMxQQebZxYlcMuUFwWZFWolZrpmZHxsIRd8aaji1tJIs9WkFGxj3/gm9EoIF0oE2slbbK+UJaZ6sI2wAWwEmXEbQFHy3DBPIQKJ/LwOBCGTPryBwiNVnWf1HgVXo8PRhF4iQx/9Jw/RObhZ7gb9J10tQ5wBOpPdtEe6uAF9HhnzsjX57UcFIfv17OidVSg6l0JfmODKTsQ4tSt9VENZ2WgbZHTA7JeZI7TLs9ZUhNuFF8/hSyZAbGNykL1z9qHwRiPQDyZLKTV09flzg1qa0aXTCa5ZmGFtCyICkyn17QCb8xXOxC1O/c2FKtbIXSAfNAZqDRRfXtfjV+HJ3p5tLxv4Hx0kxItzRMhV2fVjWj1FEwaGwz2JCNdrTnXLQim7SbH1vxti3e5Rvs8GkM456Uhw0CbSbNNKSdmbSrwEfG9AGHYX6/XtBGllTn2q7s1wVOHYcnuMJYkx6gqlCXhn4SU=
  password:
    secure: Zx4yn1f9dgSgvTZgzekCZYUGeq3oyrx3zUbBIt3EFcfMRt3ZSOGPGJqlYHe5HwyulgceHU5hyarJVsML2pr9ZD/Ni28acaEQao0lWbZyLw1Y2ueEeqwwapcvSTuIksWceDIXTY4lrv11NujDWbGDoel/izVoTf19sgQRHjh6b9d9FFa/awBg+fH228E4CFtAiO45RZzUTeppwdudM9wZTRfxtR5v6xCBdZPiQa2m0bajnVMXICS1BXI44v2mGMDFSUHp1X+Xt/u0H5v0soAOPTLv/wyetIlXF5WGCVj5KyinQ9HxzGG2LWc2y35zbd7f82NIVHWBCphw5SUpt5jj/2q9zq/Fit4OKw7PmKf9nlz2DVL90c38oiyVpXSI9JawYiMWQf90MColt2+hI9l9ncTHkP/zgtqyAZPOz7ZEwaDTGGvJvraR2uZ2vaI2KrIUZSS6kgdJthR9qhbnuOc+QmX2Vw/xu/XPDDcQJdPTO5eccFsoploO8hQ1sDYL+ms+V7up02OfF/jR+mwTfVx6pArOuDT933o+52wQ/oUVFKlGmk6UX7zxE4ktalK4E5528Ms2qeiJ2BcfER9peSvn/GMZSI5EfkWyvYipPf8cJcxZK0mggyKM5crVB+rGpdVSMRmbjboe0SvUp/BW/zkSLSD82o0F/g4Xz3ij64Ijoso=
